# This allows kustomize controller to assume an IAM role that has permissiosn to KMS for SOPS decryption
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/staging-kustomize-controller
